---
- name: download cert-manager
  ansible.builtin.get_url:
    url: https://github.com/cert-manager/cert-manager/releases/download/v1.9.1/cert-manager.yaml
    #url: https://github.com/cert-manager/cert-manager/releases/download/v1.10.1/cert-manager.yaml
    dest: /root/install
    mode: '0644'
    backup: true
  tags:
    - cert-manager_download

- name: Apply cert-manager to k8s
  kubernetes.core.k8s:
    state: present
    src: /root/install/cert-manager.yaml
  tags:
    - cert-manager_install

- include_tasks: wait2complete.yml
  vars:
    namespace: cert-manager
  tags:
    - cert-manager-wait
  when: not ansible_check_mode
