---
- name: add cert-manager repository
  kubernetes.core.helm_repository:
    name: "{{ rke2_certmanager_helm_repository_name }}"
    repo_url: "{{ rke2_certmanager_helm_repository_url }}"

- name: install cert-manager
  kubernetes.core.helm:
    timeout: 10m
    release_namespace: cert-manager
    release_name: cert-manager
    create_namespace: true
    chart_ref: jetstack/cert-manager
    chart_version: "{{ rke2_certmanager_version }}"
    set_values:
      - value: installCRDs=true
  tags:
    - cert-manager_install

- include_tasks: wait2complete.yml
  vars:
    namespace: cert-manager
  tags:
    - cert-manager-wait
  when: not ansible_check_mode
