---
- name: Add cert-manager repository
  kubernetes.core.helm_repository:
    name: "{{ rke2_certmanager_helm_repository_name }}"
    repo_url: "{{ rke2_certmanager_helm_repository_url }}"

- name: Check the last modified time of the Helm repo cache file
  ansible.builtin.stat:
    path: "{{ ansible_env.HOME }}/.cache/helm/repository/jetstack-index.yaml"
  register: repo_cache

- name: Update the repository cache
  kubernetes.core.helm:
    name: dummy
    namespace: kube-system
    state: absent
    update_repo_cache: true
  when: (repo_cache.stat.mtime | default(0)) < (ansible_date_time.epoch | int - 86400)

- name: Install cert-manager
  kubernetes.core.helm:
    timeout: 10m
    release_namespace: cert-manager
    release_name: cert-manager
    create_namespace: true
    chart_ref: jetstack/cert-manager
    chart_version: "{{ rke2_certmanager_version }}"
    set_values:
      - value: installCRDs=true
  tags:
    - cert-manager_install

- name: Wait for installation to complete
  ansible.builtin.include_tasks: wait2complete.yml
  vars:
    namespace: cert-manager
  tags:
    - cert-manager-wait
  when: not ansible_check_mode
