---
- name: download local-path-provisioner
  ansible.builtin.get_url:
    url: https://raw.githubusercontent.com/rancher/local-path-provisioner/v0.0.24/deploy/local-path-storage.yaml
    dest: /root/install
    mode: '0644'
    backup: true
  tags:
    - local-path-provisioner_download

- name: apply local-path-provisioner to k8s
  kubernetes.core.k8s:
    state: present
    src: /root/install/local-path-storage.yaml
  tags:
    - local-path-provisioner_install

- include: wait2complete.yml
  vars:
    namespace: local-path-storage
  tags:
    - local-path-provisioner-wait
  when: not ansible_check_mode
