---
- name: Check system resources
  ansible.builtin.assert:
    that:
      - ansible_processor_vcpus >= 2
        # There is some, not exact, reserved memory
        # which is not accessible to userspace. Setting
        # 4096 won't pass this assertion.
      - ansible_memtotal_mb >= 3900
    msg: RKE2 (kubernetes) needs at last two CPU and 4GB RAM
  tags:
    - rke2
    - resources_assertion

# https://docs.rke2.io/advanced
- name: Create /etc/default/rke2-server|agent
  ansible.builtin.template:
    src: "rke2-server-agent.j2"
    dest: "/etc/default/{{ item }}"
    owner: root
    group: root
    mode: '0644'
  with_items:
    - rke2-server
    - rke2-agent
  tags:
    - rke2
    - http_proxy
  when:
    proxy is defined

- name: Install rke2
  ansible.builtin.include_tasks:
    file: rke2.yml
    apply:
      tags: rke2
    tags: rke2

- name: Install ingress-nginx
  ansible.builtin.include_tasks:
    file: ingress-nginx.yml
    apply:
      tags: ingress-nginx
    tags: ingress-nginx
  when: rke2_install_ingress_nginx

- name: Install local-path-provisioner
  ansible.builtin.include_tasks:
    file: local-path-provisioner.yml
    apply:
      tags: local-path-provisioner
    tags: local-path-provisioner
    when: rke2_install_local_path_provisioner

- name: Install cert-manager
  ansible.builtin.include_tasks:
    file: cert-manager.yml
    apply:
      tags: cert-manager
    tags: cert-manager
