---
- name: check system resources
  ansible.builtin.assert:
    that:
      - ansible_processor_vcpus >= 2
        # There is some, not exact, reserved memory
        # which is not accessible to userspace. Setting
        # 4096 won't pass this assertion.
      - ansible_memtotal_mb >= 3900
    msg: RKE2 (kubernetes) needs at last two CPU and 4GB RAM
  tags:
    - rke2
    - resources_assertion

# https://docs.rke2.io/advanced
- name: create /etc/default/rke2-server|agent
  template:
    src: "rke2-server-agent.j2"
    dest: "/etc/default/{{ item }}"
    owner: root
    group: root
    mode: '0644'
  with_items:
    - rke2-server
    - rke2-agent
  tags:
    - rke2
    - http_proxy
  when:
    proxy is defined

- name: install rke2
  include: rke2.yml
  tags: rke2

- name: install ingress-nginx
  include: ingress-nginx.yml
  when: rke2_install_ingress_nginx
  tags: ingress-nginx

- name: install local-path-provisioner
  include: local-path-provisioner.yml
  when: rke2_install_local_path_provisioner
  tags: ingress-nginx

- name: install cert-manager
  include: cert-manager.yml
  tags: cert-manager

