---
- name: install RKE2 prerequisites
  apt:
    name:
      - curl
      - apparmor-utils
      - iptables
      - ca-certificates
    state: latest
    cache_valid_time: 86400
  tags:
    - rke2
    - rke_packages

- name: create RKE2 config dir
  file:
    path: /etc/rancher/rke2
    state: directory
  tags:
    - rke2
    - rke2_config_dir

- name: configure RKE2 tls-san
  ansible.builtin.template:
    src: "config.j2"
    dest: "/etc/rancher/rke2/config.yaml"
  tags:
    - rke2
    - tls-san

# TODO this is only created and never used. Is it necesary?
- name: create kube config dir
  file:
    path: /root/.kube
    state: directory
  tags:
    - rke2
    - kube_config
    - kube_config_dir

- name: configure PATH to kubectl in .bashrc
  lineinfile: dest="/root/.bashrc"
              regexp="^PATH=/var/lib/rancher/rke2/bin:"
              line="PATH=/var/lib/rancher/rke2/bin:$PATH"
              state=present
  tags:
    - rke2
    - rke2_kubectl_path
    - rke2_kubectl_path_bashrc

- name: configure path to kubectl in .profile
  lineinfile: dest="/root/.profile"
              regexp="^PATH=/var/lib/rancher/rke2/bin:"
              line="PATH=/var/lib/rancher/rke2/bin:$PATH"
              state=present
              insertbefore="^mesg n 2> /dev/null || true"
  tags:
    - rke2
    - rke2_kubectl_path
    - rke2_kubectl_path_profile

- name: install helm prerequisites
  apt:
    name:
      - apt-transport-https
      - gpg
    state: latest
    update_cache: no
    cache_valid_time: 86400
  tags:
    - rke2
    - rke_packages
    - helm
    - heml_packages

- name: install heml keyring
  ansible.builtin.get_url:
    url: https://baltocdn.com/helm/signing.asc
    dest: /usr/share/keyrings/helm.asc
    mode: 0644
  tags:
    - rke2
    - rke_packages
    - helm
    - heml_packages

- name: add heml packages repository
  ansible.builtin.apt_repository:
    repo: deb [signed-by=/usr/share/keyrings/helm.asc] https://baltocdn.com/helm/stable/debian/ all main
    state: present
  tags:
    - rke2
    - rke_packages
    - heml_packages
    - helm

- name: install helm
  apt:
    name: helm
    state: latest
    cache_valid_time: 86400
  when: not ansible_check_mode # will fail in check mode if db isn't present
  tags:
    - rke2
    - rke_packages
    - helm
    - heml_packages
