---
- name: "Wait untill {{ pod_name }} in {{ namespace }} is Running (max 10min, delay=5s)" # noqa name[template]
  ansible.builtin.shell:
    cmd: |
      test `/var/lib/rancher/rke2/bin/kubectl -n {{ namespace }} get pod |grep -i {{ pod_name }} | grep Running | wc -l` -ge 1
    executable: /bin/bash
  register: prq
  until: prq.rc == 0
  retries: 120 # 10*60/5
  delay: 5
  changed_when: false
  when: pod_name is defined

- name: "Wait untill all pods in namespace {{ namespace }} are Running (max 10min, delay=5s)" # noqa name[template]
  ansible.builtin.shell:
    cmd: |
      /var/lib/rancher/rke2/bin/kubectl -n {{ namespace }} get pod -o json |jq '.items[].status.phase' |
      grep -v Succeeded | sort -u
    executable: /bin/bash
  register: prq
  until: prq.stdout == '"Running"'
  retries: 120
  delay: 5
  changed_when: false
  when: not pod_name is defined
